// Mocks generated by Mockito 5.4.5 from annotations
// in clone_brb_card/test/ui/home/widgets/account_carousel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:clone_brb_card/domain/models/account.dart' as _i2;
import 'package:clone_brb_card/ui/home/view_models/home_viewmodel.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccount_0 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountViewModel extends _i1.Mock implements _i3.AccountViewModel {
  MockAccountViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Account> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i2.Account>[],
          )
          as List<_i2.Account>);

  @override
  _i2.Account get selectedAccount =>
      (super.noSuchMethod(
            Invocation.getter(#selectedAccount),
            returnValue: _FakeAccount_0(
              this,
              Invocation.getter(#selectedAccount),
            ),
          )
          as _i2.Account);

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addAccount(_i2.Account? account) => super.noSuchMethod(
    Invocation.method(#addAccount, [account]),
    returnValueForMissingStub: null,
  );

  @override
  void addAccounts(List<_i2.Account>? accounts) => super.noSuchMethod(
    Invocation.method(#addAccounts, [accounts]),
    returnValueForMissingStub: null,
  );

  @override
  void selectAccount(int? index) => super.noSuchMethod(
    Invocation.method(#selectAccount, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> fetchAndAddAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndAddAccounts, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
